# Generated by Django 4.0 on 2021-12-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judecator',
            fields=[
                ('id_judecator', models.BigAutoField(db_column='ID_JUDECATOR', primary_key=True, serialize=False)),
                ('cnp', models.CharField(db_column='CNP', max_length=13, unique=True)),
                ('nume', models.CharField(db_column='NUME', max_length=50)),
                ('prenume', models.CharField(db_column='PRENUME', max_length=50)),
                ('telefon', models.CharField(db_column='TELEFON', max_length=13, unique=True)),
                ('email', models.CharField(db_column='EMAIL', max_length=50, unique=True)),
                ('specializare', models.CharField(db_column='SPECIALIZARE', max_length=100)),
                ('preluare_mandat', models.DateField(db_column='PRELUARE_MANDAT')),
                ('expirare_mandat', models.DateField(db_column='EXPIRARE_MANDAT')),
            ],
            options={
                'db_table': 'JUDECATORI',
                'ordering': ['prenume', 'nume'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proces',
            fields=[
                ('id_proces', models.BigAutoField(db_column='ID_PROCES', primary_key=True, serialize=False)),
                ('numar', models.CharField(db_column='NUMĂR', max_length=15, unique=True)),
                ('obiect', models.CharField(db_column='OBIECT', max_length=100)),
                ('materie_juridica', models.CharField(db_column='MATERIE_JURIDICĂ', max_length=50)),
                ('stadiu_procesual', models.CharField(db_column='STADIU_PROCESUAL', max_length=15)),
                ('reclamant', models.CharField(db_column='RECLAMANT', max_length=100)),
                ('parat', models.CharField(db_column='PÂRÂT', max_length=100)),
            ],
            options={
                'db_table': 'PROCESE',
                'ordering': ['numar'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programare',
            fields=[
                ('id_programare', models.BigAutoField(db_column='ID_PROGRAMARE', primary_key=True, serialize=False)),
                ('oras', models.CharField(db_column='ORAȘ', max_length=20)),
                ('locatie', models.CharField(db_column='LOCAȚIE', max_length=50)),
                ('sala', models.CharField(db_column='SALA', max_length=10)),
                ('data', models.DateField(db_column='DATĂ')),
                ('ora', models.TimeField(db_column='ORĂ')),
            ],
            options={
                'db_table': 'PROGRAMARI',
                'ordering': ['data', 'ora'],
                'managed': False,
            },
        ),
    ]
